name: todo_flutter
description: "A todo app built on the RG Design System."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  cloud_firestore: ^6.6.0
  firebase_auth: ^6.5.4
  firebase_core: ^4.11.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^17.3.0
  google_sign_in: ^7.2.0
  intl: any
  provider: ^6.1.5+1
  rg_design_system:
    git:
      url: https://github.com/rodrigogaleano/rg-design-system-flutter.git
      ref: main
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
  generate: true
