// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo0tp5TWPRd03vXJocdfMYKkvkpbRbMUU',
    appId: '1:268225053084:web:ef5f0b62898783d9a4c859',
    messagingSenderId: '268225053084',
    projectId: 'todo-468a3',
    authDomain: 'todo-468a3.firebaseapp.com',
    storageBucket: 'todo-468a3.firebasestorage.app',
    measurementId: 'G-RSPEBNYNNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqfMjDEesKd7armu7HHwEc1Yy5_Zz06nM',
    appId: '1:268225053084:android:7d01f942fced1af9a4c859',
    messagingSenderId: '268225053084',
    projectId: 'todo-468a3',
    storageBucket: 'todo-468a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACvAOgnl1Pboip-oYDyntvivbFspXna8o',
    appId: '1:268225053084:ios:16dfe3f263546b95a4c859',
    messagingSenderId: '268225053084',
    projectId: 'todo-468a3',
    storageBucket: 'todo-468a3.firebasestorage.app',
    iosClientId:
        '268225053084-d57ckoeh06h71pb98priqroofl14ac3j.apps.googleusercontent.com',
    iosBundleId: 'com.rodrigogaleano.todoFlutter',
  );
}
